
alias z1='code .'
alias md='mkdir'
alias nalias='nano ~/.bash_scripts/.bash_aliases'
alias salias='source ~/.bash_scripts/.bash_aliases'
alias saifb='sudo apt install --fix-broken'
alias saifm='sudo apt install --fix-missing'
alias gdep='. ~/.bash_scripts/git-deploy.sh'
alias gcob='. ~/.bash_scripts/git-create-branch.sh'
alias cra='. ~/.bash_scripts/setup-react.sh'
alias clean-nm='. ~/.bash_scripts/clean-nm.sh'
alias gstat='git status'
alias p3='python3'
alias dpi='sudo dpkg -i'
alias dpid='sudo dpkg -i Downlads/'
