alias nalias='nano ~/.bash_aliases'
alias salias='source ~/.bash_aliases'
alias saifb='sudo apt install --fix-broken'
alias saifm='sudo apt install --fix-missing'
alias g-dep='. ~/.bash_scripts/git-deploy.sh'
alias g-new='. ~/.bash_scripts/git-create-branch.sh'
alias cra='. ~/.bash_scripts/setup-react.sh'
alias clean-nm='. ~/.bash_scripts/clean-nm.sh'
