alias nalias='nano ~/.bash_aliases'
alias salias='source ~/.bash_aliases'
alias saifb='sudo apt install --fix-broken'
alias git-deploy='. ~/bin/git-deploy'
alias git-create='. ~/bin/git-create-branch'
alias create-react-app='. ~/bin/create-react-app'
alias crfs='. ~/bin/create-react-file-structure'
alias clean-nm='. ~/bin/clean-nm'
# alias ='. ~/bin/'

